name: social-media-fastapi

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    environment:
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=test123
      - DB_USERNAME=postgres
      - DB_NAME=social-media-db
      - SECRET_KEY=d7af774858d64f46ddd02d1184b1f44d8d7793f94a79344094b0022c13d1fd07
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=social-media-db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: