name: Build and Deploy Code
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling Github Repository
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Installing Dependencies
        run: pip install -r requirements.txt
      - name: Testing with PyTest
        run: |
          pip install pytest
          pytest